### ISSUE TITLE
19. Create Instructor Class

### ISSUE THREAD

**Issue by dliu84** [patelshiv1524/DevFusion-iOS-Android#29]
As an instructor I want to manage my profile and the courses I teach so that I can effectively track student progress and update course content.

Acceptance Criteria:

1. The Instructor class should have the following attributes:

    instructorID: a unique identifier for each instructor.
    name: the instructor’s full name.
    email: a valid and unique email address.
    password: a securely hashed password for authentication.
    courses: a list of courses the instructor is teaching (connected to the Courses class).

2. The Instructor class should provide the following methods:

    __init__(): to initialize an instructor with the necessary attributes.
    addCourse(): to allow the instructor to create and add new courses.
    updateCourse(): to allow the instructor to update the content or information for existing courses.
    removeCourse(): to remove a course from the platform.
    viewStudents(): to list students enrolled in the instructor's courses.

**Comment by patelshiv1524** [comment]
Hi Di, In order to see all the issues in our Project kanban board, while you are creating issues you needd to add or assigne them to the respective project and milestone.
